// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface AppDemoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.AppDemo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */
  int getProjectsCount();
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */
  boolean containsProjects(
      java.lang.String key);
  /**
   * Use {@link #getProjectsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.dalong.userappservice.Project>
  getProjects();
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */
  java.util.Map<java.lang.String, com.dalong.userappservice.Project>
  getProjectsMap();
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  com.dalong.userappservice.Project getProjectsOrDefault(
      java.lang.String key,
      com.dalong.userappservice.Project defaultValue);
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  com.dalong.userappservice.Project getProjectsOrThrow(
      java.lang.String key);

  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  boolean hasUserrequest();
  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  com.dalong.userappservice.UserRequest getUserrequest();
  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  com.dalong.userappservice.UserRequestOrBuilder getUserrequestOrBuilder();

  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  boolean hasPersonrequest();
  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  com.dalong.userappservice.PersonRequest getPersonrequest();
  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  com.dalong.userappservice.PersonRequestOrBuilder getPersonrequestOrBuilder();

  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  boolean hasPlatformrequest();
  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  com.dalong.userappservice.PlatformRequest getPlatformrequest();
  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  com.dalong.userappservice.PlatformRequestOrBuilder getPlatformrequestOrBuilder();

  public com.dalong.userappservice.AppDemo.RequestCase getRequestCase();
}
