// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

/**
 * Protobuf type {@code userservice.AppDemo}
 */
public  final class AppDemo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:userservice.AppDemo)
    AppDemoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppDemo.newBuilder() to construct.
  private AppDemo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppDemo() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppDemo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.dalong.userappservice.UserRequest.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((com.dalong.userappservice.UserRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.dalong.userappservice.UserRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dalong.userappservice.UserRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            com.dalong.userappservice.PersonRequest.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((com.dalong.userappservice.PersonRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.dalong.userappservice.PersonRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dalong.userappservice.PersonRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          case 26: {
            com.dalong.userappservice.PlatformRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((com.dalong.userappservice.PlatformRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.dalong.userappservice.PlatformRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dalong.userappservice.PlatformRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              projects_ = com.google.protobuf.MapField.newMapField(
                  ProjectsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.dalong.userappservice.Project>
            projects__ = input.readMessage(
                ProjectsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            projects_.getMutableMap().put(
                projects__.getKey(), projects__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetProjects();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dalong.userappservice.AppDemo.class, com.dalong.userappservice.AppDemo.Builder.class);
  }

  private int bitField0_;
  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite {
    USERREQUEST(1),
    PERSONREQUEST(2),
    PLATFORMREQUEST(3),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return USERREQUEST;
        case 2: return PERSONREQUEST;
        case 3: return PLATFORMREQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int PROJECTS_FIELD_NUMBER = 4;
  private static final class ProjectsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.dalong.userappservice.Project> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.dalong.userappservice.Project>newDefaultInstance(
                com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_ProjectsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.dalong.userappservice.Project.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.dalong.userappservice.Project> projects_;
  private com.google.protobuf.MapField<java.lang.String, com.dalong.userappservice.Project>
  internalGetProjects() {
    if (projects_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ProjectsDefaultEntryHolder.defaultEntry);
    }
    return projects_;
  }

  public int getProjectsCount() {
    return internalGetProjects().getMap().size();
  }
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  public boolean containsProjects(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetProjects().getMap().containsKey(key);
  }
  /**
   * Use {@link #getProjectsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.dalong.userappservice.Project> getProjects() {
    return getProjectsMap();
  }
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  public java.util.Map<java.lang.String, com.dalong.userappservice.Project> getProjectsMap() {
    return internalGetProjects().getMap();
  }
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  public com.dalong.userappservice.Project getProjectsOrDefault(
      java.lang.String key,
      com.dalong.userappservice.Project defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.dalong.userappservice.Project> map =
        internalGetProjects().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
   */

  public com.dalong.userappservice.Project getProjectsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.dalong.userappservice.Project> map =
        internalGetProjects().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int USERREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  public boolean hasUserrequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  public com.dalong.userappservice.UserRequest getUserrequest() {
    if (requestCase_ == 1) {
       return (com.dalong.userappservice.UserRequest) request_;
    }
    return com.dalong.userappservice.UserRequest.getDefaultInstance();
  }
  /**
   * <code>.userservice.UserRequest userrequest = 1;</code>
   */
  public com.dalong.userappservice.UserRequestOrBuilder getUserrequestOrBuilder() {
    if (requestCase_ == 1) {
       return (com.dalong.userappservice.UserRequest) request_;
    }
    return com.dalong.userappservice.UserRequest.getDefaultInstance();
  }

  public static final int PERSONREQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  public boolean hasPersonrequest() {
    return requestCase_ == 2;
  }
  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  public com.dalong.userappservice.PersonRequest getPersonrequest() {
    if (requestCase_ == 2) {
       return (com.dalong.userappservice.PersonRequest) request_;
    }
    return com.dalong.userappservice.PersonRequest.getDefaultInstance();
  }
  /**
   * <code>.userservice.PersonRequest personrequest = 2;</code>
   */
  public com.dalong.userappservice.PersonRequestOrBuilder getPersonrequestOrBuilder() {
    if (requestCase_ == 2) {
       return (com.dalong.userappservice.PersonRequest) request_;
    }
    return com.dalong.userappservice.PersonRequest.getDefaultInstance();
  }

  public static final int PLATFORMREQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  public boolean hasPlatformrequest() {
    return requestCase_ == 3;
  }
  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  public com.dalong.userappservice.PlatformRequest getPlatformrequest() {
    if (requestCase_ == 3) {
       return (com.dalong.userappservice.PlatformRequest) request_;
    }
    return com.dalong.userappservice.PlatformRequest.getDefaultInstance();
  }
  /**
   * <code>.userservice.PlatformRequest platformrequest = 3;</code>
   */
  public com.dalong.userappservice.PlatformRequestOrBuilder getPlatformrequestOrBuilder() {
    if (requestCase_ == 3) {
       return (com.dalong.userappservice.PlatformRequest) request_;
    }
    return com.dalong.userappservice.PlatformRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.dalong.userappservice.UserRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (com.dalong.userappservice.PersonRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (com.dalong.userappservice.PlatformRequest) request_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProjects(),
        ProjectsDefaultEntryHolder.defaultEntry,
        4);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.dalong.userappservice.UserRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.dalong.userappservice.PersonRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.dalong.userappservice.PlatformRequest) request_);
    }
    for (java.util.Map.Entry<java.lang.String, com.dalong.userappservice.Project> entry
         : internalGetProjects().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.dalong.userappservice.Project>
      projects__ = ProjectsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, projects__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dalong.userappservice.AppDemo)) {
      return super.equals(obj);
    }
    com.dalong.userappservice.AppDemo other = (com.dalong.userappservice.AppDemo) obj;

    boolean result = true;
    result = result && internalGetProjects().equals(
        other.internalGetProjects());
    result = result && getRequestCase().equals(
        other.getRequestCase());
    if (!result) return false;
    switch (requestCase_) {
      case 1:
        result = result && getUserrequest()
            .equals(other.getUserrequest());
        break;
      case 2:
        result = result && getPersonrequest()
            .equals(other.getPersonrequest());
        break;
      case 3:
        result = result && getPlatformrequest()
            .equals(other.getPlatformrequest());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetProjects().getMap().isEmpty()) {
      hash = (37 * hash) + PROJECTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProjects().hashCode();
    }
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + USERREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUserrequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + PERSONREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getPersonrequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PLATFORMREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getPlatformrequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dalong.userappservice.AppDemo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dalong.userappservice.AppDemo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.AppDemo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.AppDemo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dalong.userappservice.AppDemo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code userservice.AppDemo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:userservice.AppDemo)
      com.dalong.userappservice.AppDemoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetProjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableProjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dalong.userappservice.AppDemo.class, com.dalong.userappservice.AppDemo.Builder.class);
    }

    // Construct using com.dalong.userappservice.AppDemo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableProjects().clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dalong.userappservice.AppService.internal_static_userservice_AppDemo_descriptor;
    }

    public com.dalong.userappservice.AppDemo getDefaultInstanceForType() {
      return com.dalong.userappservice.AppDemo.getDefaultInstance();
    }

    public com.dalong.userappservice.AppDemo build() {
      com.dalong.userappservice.AppDemo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dalong.userappservice.AppDemo buildPartial() {
      com.dalong.userappservice.AppDemo result = new com.dalong.userappservice.AppDemo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.projects_ = internalGetProjects();
      result.projects_.makeImmutable();
      if (requestCase_ == 1) {
        if (userrequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = userrequestBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (personrequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = personrequestBuilder_.build();
        }
      }
      if (requestCase_ == 3) {
        if (platformrequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = platformrequestBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dalong.userappservice.AppDemo) {
        return mergeFrom((com.dalong.userappservice.AppDemo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dalong.userappservice.AppDemo other) {
      if (other == com.dalong.userappservice.AppDemo.getDefaultInstance()) return this;
      internalGetMutableProjects().mergeFrom(
          other.internalGetProjects());
      switch (other.getRequestCase()) {
        case USERREQUEST: {
          mergeUserrequest(other.getUserrequest());
          break;
        }
        case PERSONREQUEST: {
          mergePersonrequest(other.getPersonrequest());
          break;
        }
        case PLATFORMREQUEST: {
          mergePlatformrequest(other.getPlatformrequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dalong.userappservice.AppDemo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dalong.userappservice.AppDemo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.dalong.userappservice.Project> projects_;
    private com.google.protobuf.MapField<java.lang.String, com.dalong.userappservice.Project>
    internalGetProjects() {
      if (projects_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProjectsDefaultEntryHolder.defaultEntry);
      }
      return projects_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.dalong.userappservice.Project>
    internalGetMutableProjects() {
      onChanged();;
      if (projects_ == null) {
        projects_ = com.google.protobuf.MapField.newMapField(
            ProjectsDefaultEntryHolder.defaultEntry);
      }
      if (!projects_.isMutable()) {
        projects_ = projects_.copy();
      }
      return projects_;
    }

    public int getProjectsCount() {
      return internalGetProjects().getMap().size();
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public boolean containsProjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProjects().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProjectsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.dalong.userappservice.Project> getProjects() {
      return getProjectsMap();
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public java.util.Map<java.lang.String, com.dalong.userappservice.Project> getProjectsMap() {
      return internalGetProjects().getMap();
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public com.dalong.userappservice.Project getProjectsOrDefault(
        java.lang.String key,
        com.dalong.userappservice.Project defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.dalong.userappservice.Project> map =
          internalGetProjects().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public com.dalong.userappservice.Project getProjectsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.dalong.userappservice.Project> map =
          internalGetProjects().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearProjects() {
      internalGetMutableProjects().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public Builder removeProjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProjects().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.dalong.userappservice.Project>
    getMutableProjects() {
      return internalGetMutableProjects().getMutableMap();
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */
    public Builder putProjects(
        java.lang.String key,
        com.dalong.userappservice.Project value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProjects().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .userservice.Project&gt; projects = 4;</code>
     */

    public Builder putAllProjects(
        java.util.Map<java.lang.String, com.dalong.userappservice.Project> values) {
      internalGetMutableProjects().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.UserRequest, com.dalong.userappservice.UserRequest.Builder, com.dalong.userappservice.UserRequestOrBuilder> userrequestBuilder_;
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public boolean hasUserrequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public com.dalong.userappservice.UserRequest getUserrequest() {
      if (userrequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.dalong.userappservice.UserRequest) request_;
        }
        return com.dalong.userappservice.UserRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return userrequestBuilder_.getMessage();
        }
        return com.dalong.userappservice.UserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public Builder setUserrequest(com.dalong.userappservice.UserRequest value) {
      if (userrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        userrequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public Builder setUserrequest(
        com.dalong.userappservice.UserRequest.Builder builderForValue) {
      if (userrequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        userrequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public Builder mergeUserrequest(com.dalong.userappservice.UserRequest value) {
      if (userrequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.dalong.userappservice.UserRequest.getDefaultInstance()) {
          request_ = com.dalong.userappservice.UserRequest.newBuilder((com.dalong.userappservice.UserRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          userrequestBuilder_.mergeFrom(value);
        }
        userrequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public Builder clearUserrequest() {
      if (userrequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        userrequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public com.dalong.userappservice.UserRequest.Builder getUserrequestBuilder() {
      return getUserrequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    public com.dalong.userappservice.UserRequestOrBuilder getUserrequestOrBuilder() {
      if ((requestCase_ == 1) && (userrequestBuilder_ != null)) {
        return userrequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.dalong.userappservice.UserRequest) request_;
        }
        return com.dalong.userappservice.UserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.UserRequest userrequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.UserRequest, com.dalong.userappservice.UserRequest.Builder, com.dalong.userappservice.UserRequestOrBuilder> 
        getUserrequestFieldBuilder() {
      if (userrequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.dalong.userappservice.UserRequest.getDefaultInstance();
        }
        userrequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dalong.userappservice.UserRequest, com.dalong.userappservice.UserRequest.Builder, com.dalong.userappservice.UserRequestOrBuilder>(
                (com.dalong.userappservice.UserRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return userrequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.PersonRequest, com.dalong.userappservice.PersonRequest.Builder, com.dalong.userappservice.PersonRequestOrBuilder> personrequestBuilder_;
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public boolean hasPersonrequest() {
      return requestCase_ == 2;
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public com.dalong.userappservice.PersonRequest getPersonrequest() {
      if (personrequestBuilder_ == null) {
        if (requestCase_ == 2) {
          return (com.dalong.userappservice.PersonRequest) request_;
        }
        return com.dalong.userappservice.PersonRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return personrequestBuilder_.getMessage();
        }
        return com.dalong.userappservice.PersonRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public Builder setPersonrequest(com.dalong.userappservice.PersonRequest value) {
      if (personrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        personrequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public Builder setPersonrequest(
        com.dalong.userappservice.PersonRequest.Builder builderForValue) {
      if (personrequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        personrequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public Builder mergePersonrequest(com.dalong.userappservice.PersonRequest value) {
      if (personrequestBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != com.dalong.userappservice.PersonRequest.getDefaultInstance()) {
          request_ = com.dalong.userappservice.PersonRequest.newBuilder((com.dalong.userappservice.PersonRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          personrequestBuilder_.mergeFrom(value);
        }
        personrequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public Builder clearPersonrequest() {
      if (personrequestBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        personrequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public com.dalong.userappservice.PersonRequest.Builder getPersonrequestBuilder() {
      return getPersonrequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    public com.dalong.userappservice.PersonRequestOrBuilder getPersonrequestOrBuilder() {
      if ((requestCase_ == 2) && (personrequestBuilder_ != null)) {
        return personrequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (com.dalong.userappservice.PersonRequest) request_;
        }
        return com.dalong.userappservice.PersonRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.PersonRequest personrequest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.PersonRequest, com.dalong.userappservice.PersonRequest.Builder, com.dalong.userappservice.PersonRequestOrBuilder> 
        getPersonrequestFieldBuilder() {
      if (personrequestBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = com.dalong.userappservice.PersonRequest.getDefaultInstance();
        }
        personrequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dalong.userappservice.PersonRequest, com.dalong.userappservice.PersonRequest.Builder, com.dalong.userappservice.PersonRequestOrBuilder>(
                (com.dalong.userappservice.PersonRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return personrequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.PlatformRequest, com.dalong.userappservice.PlatformRequest.Builder, com.dalong.userappservice.PlatformRequestOrBuilder> platformrequestBuilder_;
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public boolean hasPlatformrequest() {
      return requestCase_ == 3;
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public com.dalong.userappservice.PlatformRequest getPlatformrequest() {
      if (platformrequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (com.dalong.userappservice.PlatformRequest) request_;
        }
        return com.dalong.userappservice.PlatformRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return platformrequestBuilder_.getMessage();
        }
        return com.dalong.userappservice.PlatformRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public Builder setPlatformrequest(com.dalong.userappservice.PlatformRequest value) {
      if (platformrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        platformrequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public Builder setPlatformrequest(
        com.dalong.userappservice.PlatformRequest.Builder builderForValue) {
      if (platformrequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        platformrequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public Builder mergePlatformrequest(com.dalong.userappservice.PlatformRequest value) {
      if (platformrequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != com.dalong.userappservice.PlatformRequest.getDefaultInstance()) {
          request_ = com.dalong.userappservice.PlatformRequest.newBuilder((com.dalong.userappservice.PlatformRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          platformrequestBuilder_.mergeFrom(value);
        }
        platformrequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public Builder clearPlatformrequest() {
      if (platformrequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        platformrequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public com.dalong.userappservice.PlatformRequest.Builder getPlatformrequestBuilder() {
      return getPlatformrequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    public com.dalong.userappservice.PlatformRequestOrBuilder getPlatformrequestOrBuilder() {
      if ((requestCase_ == 3) && (platformrequestBuilder_ != null)) {
        return platformrequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (com.dalong.userappservice.PlatformRequest) request_;
        }
        return com.dalong.userappservice.PlatformRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.userservice.PlatformRequest platformrequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dalong.userappservice.PlatformRequest, com.dalong.userappservice.PlatformRequest.Builder, com.dalong.userappservice.PlatformRequestOrBuilder> 
        getPlatformrequestFieldBuilder() {
      if (platformrequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = com.dalong.userappservice.PlatformRequest.getDefaultInstance();
        }
        platformrequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dalong.userappservice.PlatformRequest, com.dalong.userappservice.PlatformRequest.Builder, com.dalong.userappservice.PlatformRequestOrBuilder>(
                (com.dalong.userappservice.PlatformRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return platformrequestBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:userservice.AppDemo)
  }

  // @@protoc_insertion_point(class_scope:userservice.AppDemo)
  private static final com.dalong.userappservice.AppDemo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dalong.userappservice.AppDemo();
  }

  public static com.dalong.userappservice.AppDemo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppDemo>
      PARSER = new com.google.protobuf.AbstractParser<AppDemo>() {
    public AppDemo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppDemo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppDemo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppDemo> getParserForType() {
    return PARSER;
  }

  public com.dalong.userappservice.AppDemo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

