// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageresult = 1;</code>
   */
  java.lang.String getMessageresult();
  /**
   * <code>string messageresult = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageresultBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
