// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

/**
 * Protobuf type {@code userservice.MixInfo}
 */
public  final class MixInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:userservice.MixInfo)
    MixInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MixInfo.newBuilder() to construct.
  private MixInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MixInfo() {
    username_ = "";
    orgname_ = "";
    orgid_ = "";
    enterprise_ = "";
    enterpriseid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MixInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orgname_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            orgid_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            enterprise_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            enterpriseid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dalong.userappservice.AppService.internal_static_userservice_MixInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dalong.userappservice.AppService.internal_static_userservice_MixInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dalong.userappservice.MixInfo.class, com.dalong.userappservice.MixInfo.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 1;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object orgname_;
  /**
   * <code>string orgname = 2;</code>
   */
  public java.lang.String getOrgname() {
    java.lang.Object ref = orgname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orgname_ = s;
      return s;
    }
  }
  /**
   * <code>string orgname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOrgnameBytes() {
    java.lang.Object ref = orgname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orgname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGID_FIELD_NUMBER = 3;
  private volatile java.lang.Object orgid_;
  /**
   * <code>string orgid = 3;</code>
   */
  public java.lang.String getOrgid() {
    java.lang.Object ref = orgid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orgid_ = s;
      return s;
    }
  }
  /**
   * <code>string orgid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOrgidBytes() {
    java.lang.Object ref = orgid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orgid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTERPRISE_FIELD_NUMBER = 4;
  private volatile java.lang.Object enterprise_;
  /**
   * <code>string enterprise = 4;</code>
   */
  public java.lang.String getEnterprise() {
    java.lang.Object ref = enterprise_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      enterprise_ = s;
      return s;
    }
  }
  /**
   * <code>string enterprise = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEnterpriseBytes() {
    java.lang.Object ref = enterprise_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      enterprise_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTERPRISEID_FIELD_NUMBER = 5;
  private volatile java.lang.Object enterpriseid_;
  /**
   * <code>string enterpriseid = 5;</code>
   */
  public java.lang.String getEnterpriseid() {
    java.lang.Object ref = enterpriseid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      enterpriseid_ = s;
      return s;
    }
  }
  /**
   * <code>string enterpriseid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getEnterpriseidBytes() {
    java.lang.Object ref = enterpriseid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      enterpriseid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (!getOrgnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orgname_);
    }
    if (!getOrgidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orgid_);
    }
    if (!getEnterpriseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, enterprise_);
    }
    if (!getEnterpriseidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, enterpriseid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (!getOrgnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orgname_);
    }
    if (!getOrgidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orgid_);
    }
    if (!getEnterpriseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, enterprise_);
    }
    if (!getEnterpriseidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, enterpriseid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dalong.userappservice.MixInfo)) {
      return super.equals(obj);
    }
    com.dalong.userappservice.MixInfo other = (com.dalong.userappservice.MixInfo) obj;

    boolean result = true;
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && getOrgname()
        .equals(other.getOrgname());
    result = result && getOrgid()
        .equals(other.getOrgid());
    result = result && getEnterprise()
        .equals(other.getEnterprise());
    result = result && getEnterpriseid()
        .equals(other.getEnterpriseid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + ORGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getOrgname().hashCode();
    hash = (37 * hash) + ORGID_FIELD_NUMBER;
    hash = (53 * hash) + getOrgid().hashCode();
    hash = (37 * hash) + ENTERPRISE_FIELD_NUMBER;
    hash = (53 * hash) + getEnterprise().hashCode();
    hash = (37 * hash) + ENTERPRISEID_FIELD_NUMBER;
    hash = (53 * hash) + getEnterpriseid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dalong.userappservice.MixInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dalong.userappservice.MixInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.MixInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dalong.userappservice.MixInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dalong.userappservice.MixInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code userservice.MixInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:userservice.MixInfo)
      com.dalong.userappservice.MixInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dalong.userappservice.AppService.internal_static_userservice_MixInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dalong.userappservice.AppService.internal_static_userservice_MixInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dalong.userappservice.MixInfo.class, com.dalong.userappservice.MixInfo.Builder.class);
    }

    // Construct using com.dalong.userappservice.MixInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      username_ = "";

      orgname_ = "";

      orgid_ = "";

      enterprise_ = "";

      enterpriseid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dalong.userappservice.AppService.internal_static_userservice_MixInfo_descriptor;
    }

    public com.dalong.userappservice.MixInfo getDefaultInstanceForType() {
      return com.dalong.userappservice.MixInfo.getDefaultInstance();
    }

    public com.dalong.userappservice.MixInfo build() {
      com.dalong.userappservice.MixInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dalong.userappservice.MixInfo buildPartial() {
      com.dalong.userappservice.MixInfo result = new com.dalong.userappservice.MixInfo(this);
      result.username_ = username_;
      result.orgname_ = orgname_;
      result.orgid_ = orgid_;
      result.enterprise_ = enterprise_;
      result.enterpriseid_ = enterpriseid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dalong.userappservice.MixInfo) {
        return mergeFrom((com.dalong.userappservice.MixInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dalong.userappservice.MixInfo other) {
      if (other == com.dalong.userappservice.MixInfo.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getOrgname().isEmpty()) {
        orgname_ = other.orgname_;
        onChanged();
      }
      if (!other.getOrgid().isEmpty()) {
        orgid_ = other.orgid_;
        onChanged();
      }
      if (!other.getEnterprise().isEmpty()) {
        enterprise_ = other.enterprise_;
        onChanged();
      }
      if (!other.getEnterpriseid().isEmpty()) {
        enterpriseid_ = other.enterpriseid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dalong.userappservice.MixInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dalong.userappservice.MixInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orgname_ = "";
    /**
     * <code>string orgname = 2;</code>
     */
    public java.lang.String getOrgname() {
      java.lang.Object ref = orgname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orgname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orgname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrgnameBytes() {
      java.lang.Object ref = orgname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orgname = 2;</code>
     */
    public Builder setOrgname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orgname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orgname = 2;</code>
     */
    public Builder clearOrgname() {
      
      orgname_ = getDefaultInstance().getOrgname();
      onChanged();
      return this;
    }
    /**
     * <code>string orgname = 2;</code>
     */
    public Builder setOrgnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orgname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orgid_ = "";
    /**
     * <code>string orgid = 3;</code>
     */
    public java.lang.String getOrgid() {
      java.lang.Object ref = orgid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orgid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orgid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrgidBytes() {
      java.lang.Object ref = orgid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orgid = 3;</code>
     */
    public Builder setOrgid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orgid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orgid = 3;</code>
     */
    public Builder clearOrgid() {
      
      orgid_ = getDefaultInstance().getOrgid();
      onChanged();
      return this;
    }
    /**
     * <code>string orgid = 3;</code>
     */
    public Builder setOrgidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orgid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object enterprise_ = "";
    /**
     * <code>string enterprise = 4;</code>
     */
    public java.lang.String getEnterprise() {
      java.lang.Object ref = enterprise_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enterprise_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string enterprise = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEnterpriseBytes() {
      java.lang.Object ref = enterprise_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enterprise_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string enterprise = 4;</code>
     */
    public Builder setEnterprise(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      enterprise_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string enterprise = 4;</code>
     */
    public Builder clearEnterprise() {
      
      enterprise_ = getDefaultInstance().getEnterprise();
      onChanged();
      return this;
    }
    /**
     * <code>string enterprise = 4;</code>
     */
    public Builder setEnterpriseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      enterprise_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object enterpriseid_ = "";
    /**
     * <code>string enterpriseid = 5;</code>
     */
    public java.lang.String getEnterpriseid() {
      java.lang.Object ref = enterpriseid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enterpriseid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string enterpriseid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEnterpriseidBytes() {
      java.lang.Object ref = enterpriseid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enterpriseid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string enterpriseid = 5;</code>
     */
    public Builder setEnterpriseid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      enterpriseid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string enterpriseid = 5;</code>
     */
    public Builder clearEnterpriseid() {
      
      enterpriseid_ = getDefaultInstance().getEnterpriseid();
      onChanged();
      return this;
    }
    /**
     * <code>string enterpriseid = 5;</code>
     */
    public Builder setEnterpriseidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      enterpriseid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:userservice.MixInfo)
  }

  // @@protoc_insertion_point(class_scope:userservice.MixInfo)
  private static final com.dalong.userappservice.MixInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dalong.userappservice.MixInfo();
  }

  public static com.dalong.userappservice.MixInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MixInfo>
      PARSER = new com.google.protobuf.AbstractParser<MixInfo>() {
    public MixInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MixInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MixInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MixInfo> getParserForType() {
    return PARSER;
  }

  public com.dalong.userappservice.MixInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

