// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface PlatformRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.PlatformRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string platformid = 1;</code>
   */
  java.lang.String getPlatformid();
  /**
   * <code>string platformid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPlatformidBytes();
}
