// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface ProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.Project)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectid = 1;</code>
   */
  java.lang.String getProjectid();
  /**
   * <code>string projectid = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectidBytes();

  /**
   * <code>string projectname = 2;</code>
   */
  java.lang.String getProjectname();
  /**
   * <code>string projectname = 2;</code>
   */
  com.google.protobuf.ByteString
      getProjectnameBytes();

  /**
   * <code>string projecttype = 3;</code>
   */
  java.lang.String getProjecttype();
  /**
   * <code>string projecttype = 3;</code>
   */
  com.google.protobuf.ByteString
      getProjecttypeBytes();
}
