// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userid = 1;</code>
   */
  java.lang.String getUserid();
  /**
   * <code>string userid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUseridBytes();
}
