// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface MessageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.MessageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageoid = 1;</code>
   */
  java.lang.String getMessageoid();
  /**
   * <code>string messageoid = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageoidBytes();
}
