// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface MixInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.MixInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string orgname = 2;</code>
   */
  java.lang.String getOrgname();
  /**
   * <code>string orgname = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrgnameBytes();

  /**
   * <code>string orgid = 3;</code>
   */
  java.lang.String getOrgid();
  /**
   * <code>string orgid = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrgidBytes();

  /**
   * <code>string enterprise = 4;</code>
   */
  java.lang.String getEnterprise();
  /**
   * <code>string enterprise = 4;</code>
   */
  com.google.protobuf.ByteString
      getEnterpriseBytes();

  /**
   * <code>string enterpriseid = 5;</code>
   */
  java.lang.String getEnterpriseid();
  /**
   * <code>string enterpriseid = 5;</code>
   */
  com.google.protobuf.ByteString
      getEnterpriseidBytes();
}
