// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string personid = 1;</code>
   */
  java.lang.String getPersonid();
  /**
   * <code>string personid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPersonidBytes();
}
