// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.dalong.userappservice;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userservice.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.userservice.MixInfo result = 3;</code>
   */
  boolean hasResult();
  /**
   * <code>.userservice.MixInfo result = 3;</code>
   */
  com.dalong.userappservice.MixInfo getResult();
  /**
   * <code>.userservice.MixInfo result = 3;</code>
   */
  com.dalong.userappservice.MixInfoOrBuilder getResultOrBuilder();
}
